### ISSUE TITLE
Ability to change default digits for a particular currency

### ISSUE THREAD

**Issue by kiranreddykasa** [zalando/jackson-datatype-money#110]
Ability to change default digits for a particular currency

## Detailed Description
For eg default digits for TWD currency is 2 but we do need to return zero  digits

## Context
Accordiing to busineess needs users can change the decimal points for specific currency

**Comment by whiskeysierra** [comment]
Your request would touch this place in the code:

https://github.com/zalando/jackson-datatype-money/blob/565402c4412f84c57a5f6f19949a4256ac336fea/src/main/java/org/zalando/jackson/datatype/money/DecimalAmountWriter.java#L16-L20

We basically allow clients to use a higher scale than the default fraction digits of the currency, but not a smaller one. I believe to remember that we did this to make sure that we always include a fraction, even if it's technically not needed. Basically `100.00` rather than `100`.

Your requirement can be rephrased in a way that you don't want this fallback to apply. I see two options:

1. We remove the fallback to the default fraction digits completely and leave the scale of the amount untouched.
  **Pro**: less calculations within our library and user supplied values are taken as-is
  **Cons**: amounts on the wire would sometimes have fractions and sometimes they wouldn't
2. Make that behavior configurable with the use of default fraction digits being the default.
  **Pro**: allows clients to choose what fits their requirements
  **Cons**: increases complexity of the library
3. Don't do anything, since a fraction of `x.00` is technically equivalent to `x`.
  **Pro**: no changes needed
  **Cons**: unwanted fractions, but I believe that this is a non-problem to be honest

**Comment by whiskeysierra** [comment]
@jhorstmann @AlexanderYastrebov @lukasniemeier-zalando Thoughts?

**Comment by AlexanderYastrebov** [comment]
I like option #1: no data is lost, no manipulations are done and client can display value with amount of decimal digits she wants (could be even conditional on value or something else).

**Comment by whiskeysierra** [comment]
I prefer Option 3, to be honest.

**Comment by lukasniemeier-zalando** [comment]
I vote for option 1 - leave it up to the client's code to decide

**Comment by whiskeysierra** [comment]
Ok, I'll submit to the majority.

I actually tried to remove the scaling yesterday and I realized we have two different issues then:

1. **Seemingly arbitrary scientific notation** 
   The amount of *100 EUR* will look different on the wire depending on which `MonetaryAmount` implementation is used. `FastMoney` results in `1E+2` the other two will use `100`. That's really unfortunate, but based on the fact that the `BigDecimal` returned by `amount.getNumber().numberValueExact(BigDecimal.class)` is not standardized across the different implementations and varies in scale. It can be mitigated by enabling `WRITE_BIGDECIMAL_AS_PLAIN` but that's up to our clients to enable. (Alternatively we ignore that configuration and always use `toPlainString()` ourselves.)
2. **No trailing zeros**
   All `MonetaryAmount` implementations actually call `BigDecimal#stripTrailingZeros()` on everything that is returned by `numberValueExact(BigDecimal.class)`. That means no matter what scale an application uses internally, as soon as we try to get a hold of the underlying `BigDecimal` we will get one without trailing zeros. That has the noticeable effect that you'll never see e.g. `100.00` on the wire, but always `100`. I don't know of any workaround for this.

**Comment by AlexanderYastrebov** [comment]
`DecimalAmountWriter` implements `AmountWriter<BigDecimal>` thus it returns BigDecimal so one may argue that it is up to serialization layer and client to render it as they like.

Original inquiry was about configuring decimal amount representation for particular currency which is achievable by implementing custom `AmountWriter`.

Having said that, resolution of this ticket might be to leave `DecimalAmountWriter` as it is now (least astonishment principle for existing clients) and to document and make `private MoneyModule withNumbers(final AmountWriter writer)` public to allow custom writers.

**Comment by whiskeysierra** [comment]
`AmountWriter` is also package private right now, by design.

**Comment by whiskeysierra** [comment]
@AlexanderYastrebov What you describe is basically Option 2, in a nutshell, right?

**Comment by AlexanderYastrebov** [comment]
@whiskeysierra Basically I propose not to try to predict what clients might need, but allow them to easily implement what they want

**Comment by whiskeysierra** [comment]
@kiranreddykasa I released the change as 1.1.0 to central. You're now able to implement your own, custom `AmountWriter` in which you're in full control of fraction digits.
