### ISSUE TITLE
Integration with JSR-303 and Spring Validation

### ISSUE THREAD

**Issue by KrystianLaskowskiBCF** [zalando/jackson-datatype-money#301]
I'd like to use Spring Validation all across my application. However, default deserializer kicks in before Spring Validation and JsonParseException is thrown. Is there any way that doesn't require writing custom deserializer to supress default check if fields are present?

**Comment by whiskeysierra** [comment]
JSR-303 aka Bean Validation is meant for semantic validation, i.e. are the properties of a bean (or a graph thereof) set correctly. I'd treat JSON document validation differently:

1. JSON syntax, i.e. fail if the document is not even valid JSON
2. JSON schema, i.e. fail if the document is not compliant with the schema, e.g. using OpenAPI https://opensource.zalando.com/restful-api-guidelines/#173
3. Semantic validation of the document
  - this could in theory be done on a JSON level as well, but it would be better suited to use plain java objects for this
  - this is where bean validation aka JSR-303 comes into play

What you're describing is more a number 2 problem, instead of 3.

**Comment by cberg-zalando** [comment]
@whiskeysierra Looks like the script generating a release's chaneglog is also including issues, which are closed, but not fixed.
