### ISSUE TITLE
Create LocaleProvider to resolve correctly current locale

### ISSUE THREAD

**Issue by ptahchiev** [zalando/jackson-datatype-money#71]
Hello,
the `MonetaryAmountSerlializer` currently always gets the default locale from the configuration (mine is `en_US` ):
https://github.com/zalando/jackson-datatype-money/blob/master/src/main/java/org/zalando/jackson/datatype/money/MonetaryAmountSerializer.java#L57

The problem I have is that my customers are able to change the session currency they view the website in. 

I'd like to introduce a new type (something like `LocaleProvider`) which would be injected in the constructor of the `MonetaryAmountSerializer` together with the `MonetaryAmountFormatFactory` like this:
````
    public MonetaryAmountSerializer(final MonetaryAmountFormatFactory factory, final LocaleProvider provider) {
        this.factory = factory;
        this.localeProvider = localeProvider;
    }
````
Of course you provide a default implementation which simple takes it from the configuration (the current behavior). But this way I would be able to substitute the default behaviour with my own too.

Thanks and keep up the good work :)

**Comment by whiskeysierra** [comment]
Did you take a look at
https://github.com/zalando/jackson-datatype-money/blob/master/README.md#formatting?
The locale in the configuration is not global nor static, you can overwrite
it by using an ObjectWriter.

On Oct 28, 2017 20:00, "Petar Tahchiev" <notifications@github.com> wrote:

Hello,
the MonetaryAmountSerlializer currently always gets the default locale from
the configuration (mine is en_US ):
https://github.com/zalando/jackson-datatype-money/blob/
master/src/main/java/org/zalando/jackson/datatype/money/
MonetaryAmountSerializer.java#L57

The problem I have is that my customers are able to change the session
currency they view the website in.

I'd like to introduce a new type (something like LocaleProvider) which
would be injected in the constructor of the MonetaryAmountSerializer
together with the MonetaryAmountFormatFactory like this:

    public MonetaryAmountSerializer(final MonetaryAmountFormatFactory
factory, final LocaleProvider provider) {
        this.factory = factory;
        this.localeProvider = localeProvider;
    }

Of course you provide a default implementation which simple takes it from
the configuration (the current behavior). But this way I would be able to
substitute the default behaviour with my own too.

Thanks and keep up the good work :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zalando/jackson-datatype-money/issues/71>, or mute the
thread

**Comment by ptahchiev** [comment]
Hi Willi Schönborn,

sorry - I was unaware I could change the locale via the `ObjectWriter`. I am using Spring to automatically serialize my POJOs as return values from my controllers and I don't know how I could access the `ObjectWriter`.

**Comment by whiskeysierra** [comment]
Looks like Spring doesn't allow access to the writer that they use under the hood, see [AbstractJackson2HttpMessageConverter](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/converter/json/AbstractJackson2HttpMessageConverter.java#L268):

```java

ObjectWriter objectWriter;
if (serializationView != null) {
    objectWriter = this.objectMapper.writerWithView(serializationView);
}
else if (filters != null) {
    objectWriter = this.objectMapper.writer(filters);
}
else {
    objectWriter = this.objectMapper.writer();
}
if (javaType != null && javaType.isContainerType()) {
    objectWriter = objectWriter.forType(javaType);
}
SerializationConfig config = objectWriter.getConfig();
if (contentType != null && contentType.isCompatibleWith(MediaType.TEXT_EVENT_STREAM) &&
        config.isEnabled(SerializationFeature.INDENT_OUTPUT)) {
    objectWriter = objectWriter.with(this.ssePrettyPrinter);
}
objectWriter.writeValue(generator, value);
```

**Comment by whiskeysierra** [comment]
It would be nice to get Spring to support this, somehow.

**Comment by ptahchiev** [comment]
Yes, one way is to have spring support for this, but another way is the also let jackson-datatype-money to be more flexible and provide this extra feature. Perhaps @jhoeller or @rstoyanchev might have an opinion on this.
